<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> Assert </title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="../../Assets/stylesPages.css">
    <script src="../../Assets/scriptPages.js"></script>
  </head>
  <body>
    <h1> Assert </h1>
    <p> Updated: ( 2019-08-28 / 2025-02-06 )</p>
    <nav class="sitenav">
      <a href="../../index.html">MySite > </a>
      <a href="../index.html">Node.js > </a> Assert
    </nav>
    <table class="table">
      <tr>
        <th> Methods </th>
        <th> Description </th>
      </tr>
      <tr>
        <td> <strong>assert</strong>(<strong>val:any</strong>, <i class="openable">message:str|err<div>
          <p> - <optval>str</optval>: AssertionError with message <optval>message</optval> </p>
          <p> - <optval>err</optval> throws the passed error </p>
        </div></i>) </td>
        <td>
          - if <reqval>val</reqval> evaluates falsy throws an AssertionError (or <optval>message</optval>)
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.ok(<strong>val:any</strong>, <i class="openable">message:str|err<div>
          <p> - <optval>str</optval>: AssertionError with message <optval>message</optval> </p>
          <p> - <optval>err</optval> throws the passed error </p>
        </div></i>) </td>
        <td>
          - if <reqval>val</reqval> evaluates falsy throws an AssertionError (or <optval>message</optval>)
        </td>
      </tr>



      <tr>
        <td>|</td>
        <td></td>
      </tr>
      <tr>
        <td>|</td>
        <td></td>
      </tr>
      <tr>
        <td>|</td>
        <td></td>
      </tr>

      <tr>
        <td> <strong>assert</strong>.deepEqual(<strong>actual:any</strong>, <strong>expected:any</strong>, <i>message:str|err</i>) </td>
        <td> - deeply compares the equality between the 1st and 2nd arguments (can compare objects) <br>
          - does nothing if the compared arguments are equal, otherwise throws an assertion error (optionally with the passed message) <br>
          - primitive values are compared with the 'Abstract Equality Comparison' (<mark>==</mark>) (in strict mode it uses the (<mark>===</mark>) comparison) <br>
          - only enumerable own properties are considered <br>
          - Error names and messages are always compared, even if they aren't enumerable properties <br>
          - Object wrappers are compared both as objects and unwarpped values <br>
          - Object / Map / Set properties|items are compared unordered <br>
          - does not test object prototypes <br>
          <span style="color:orangered;">- deprecated use the <mark>deepStrictEqual</mark> method instead</span>
          <span id="browserSupport" title="updated : 2019-08-30">
            <span><i class="fab fa-node-js"></i> 0.1.21 </span>
            <span><i class="fab fa-node-js"></i> 8.0.0 compares <mark>Map</mark> / <mark>Set</mark> </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.deepStrictEqual(<strong>actual:any</strong>, <strong>expected:any</strong>, <i>message:str|err</i>) </td>
        <td> - deeply compares the equality between the 1st and 2nd arguments (can compare objects) <br>
          - does nothing if the compared arguments are equal, otherwise throws an assertion error (optionally with the passed message) <br>
          - primitive values are compared with the 'Same Value Equality' (<mark>===</mark>) <br>
          - only enumerable own properties are considered <br>
          - compares enumerable own Symbol properties
          - Error names and messages are always compared, even if they aren't enumerable properties <br>
          - Object wrappers are compared both as objects and unwarpped values <br>
          - Object / Map / Set properties|items are compared unordered <br>
          - compares prototypes by using the 'Same Value Comparison' (<mark>===</mark>)
          <span id="browserSupport" title="updated : 2019-08-30">
            <span><i class="fab fa-node-js"></i> 1.2.0 </span>
            <span><i class="fab fa-node-js"></i> 8.0.0 compares <mark>Map</mark> / <mark>Set</mark> </span>
            <span><i class="fab fa-node-js"></i> 9.0.0 compares Symbols </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.doesNotReject(<strong>asyncFn|promise</strong>, <i>Class|RegExp|obj|err|fn</i>, <i>message:str</i>) </td>
        <td> - does nothing if the <strong>asyncFn|promise</strong> returns a resolved promise, otherwise throwns an assertion error (optionally with the passed message) <br>
          - if <strong>asyncFn|promise</strong> returns a rejected promise an assertion error will be thrown in any situation<br>
          - <u>(useless method according to Node.js specification)</u>
          <span id="browserSupport" title="updated : 2019-09-01">
            <span><i class="fab fa-node-js"></i> 10.0.0 </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.doesNotThrow(<strong>fn</strong>, <i>Class|RegExp|obj|err|fn</i>, <i>message:str</i>) </td>
        <td> - does nothing if the <strong>fn</strong> does NOT throw an error<br>
          - if <strong>fn</strong> throws an error an assertion error is thrown (with the passed message) in any situation <br>
          - <u>(useless method according to Node.js specification)</u>
          <span id="browserSupport" title="updated : 2019-09-01">
            <span><i class="fab fa-node-js"></i> 0.1.21 </span>
            <span><i class="fab fa-node-js"></i> 4.2.0 arrow function allowed </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.equal(<strong>actualVal:any</strong>, <strong>expectedVal:any</strong>, <i>message:str|err</i>) </td>
        <td> - tests the equality between the 1st and 2nd arguments by using the 'abstract equality comparison' (<mark>==</mark>) <br>
          - in strict mode it uses the 'same value comparison' (<mark>===</mark>) <br>
          - does nothing if the compared values are equal, otherwise throws an assertion error (optionally with the passed message) <br>
          - cannot compare objects = throws an assertion error <br>
          <span style="color:orangered;">- deprecated use the <mark>strictEqual()</mark> method instead</span>
          <span id="browserSupport" title="updated : 2019-08-29">
            <span><i class="fab fa-node-js"></i> 0.1.21 </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.fail(<i>message:str:err</i>) </td>
        <td> throws an assertion error (optionally with the passed message, default message otherwise)
          <span id="browserSupport" title="updated : 2019-08-29">
            <span><i class="fab fa-node-js"></i> 0.1.21 </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.ifError(<strong>val:any</strong>) </td>
        <td> throws an assertion error with the passed value if the value is NOT <mark>undefined</mark> or <mark>null</mark>
          <span id="browserSupport" title="updated : 2019-08-29">
            <span><i class="fab fa-node-js"></i> 0.1.97 </span>
            <span><i class="fab fa-node-js"></i> 10.0.0 before this version falsy evaluated values were same as <mark>null</mark> </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.notDeepEqual(<strong>actual:any</strong>, <strong>expected:any</strong>, <i>message:str|err</i>) </td>
        <td> - deeply compares the equality between the 1st and 2nd arguments (can compare objects) <br>
          - does nothing if the compared arguments are NOT equal, otherwise throws an assertion error (optionally with the passed message) <br>
          - primitive values are compared with the 'Abstract Equality Comparison' (<mark>==</mark>) (in strict mode it uses the (<mark>===</mark>) comparison) <br>
          - only enumerable own properties are considered <br>
          - Error names and messages are always compared, even if they aren't enumerable properties <br>
          - Object wrappers are compared both as objects and unwarpped values <br>
          - Object / Map / Set properties|items are compared unordered <br>
          - does not test object prototypes <br>
          - <span style="color:orangered;">deprecated use the <mark>notDeepStrictEqual</mark> method instead</span>
          <span id="browserSupport" title="updated : 2019-08-30">
            <span><i class="fab fa-node-js"></i> 0.1.21 </span>
            <span><i class="fab fa-node-js"></i> 8.0.0 compares <mark>Map</mark> / <mark>Set</mark> </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.notDeepStrictEqual(<strong>actual:any</strong>, <strong>expected:any</strong>, <i>message:str|err</i>) </td>
        <td> - deeply compares the equality between the 1st and 2nd arguments (can compare objects) <br>
          - does nothing if the compared arguments are NOT equal, otherwise throws an assertion error (optionally with the passed message) <br>
          - primitive values are compared with the 'Same Value Equality' (<mark>===</mark>) <br>
          - only enumerable own properties are considered <br>
          - Error names and messages are always compared, even if they aren't enumerable properties <br>
          - Object wrappers are compared both as objects and unwarpped values <br>
          - Object / Map / Set properties|items are compared unordered <br>
          - compares prototypes by using the 'Same Value Comparison' (<mark>===</mark>)
          <span id="browserSupport" title="updated : 2019-08-30">
            <span><i class="fab fa-node-js"></i> 1.2.0 </span>
            <span><i class="fab fa-node-js"></i> 8.0.0 compares <mark>Map</mark> / <mark>Set</mark> </span>
            <span><i class="fab fa-node-js"></i> 9.0.0 compares Symbols </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.notEqual(<strong>actualVal:any</strong>, <strong>expectedVal:any</strong>, <i>message:str|err</i>) </td>
        <td> - tests the equality between the 1st and 2nd arguments by using the 'abstract equality comparison' (<mark>==</mark>) <br>
          - in strict mode it uses the 'same value comparison' (<mark>===</mark>) <br>
          - does nothing if the compared values are NOT equal, otherwise throws an assertion error (optionally with the passed message) <br>
          - cannot compare objects = throws an assertion error <br>
          <span style="color:orangered;">- deprecated use the <mark>notStrictEqual()</mark> method instead</span>
          <span id="browserSupport" title="updated : 2019-08-29">
            <span><i class="fab fa-node-js"></i> 0.1.21 </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.notStrictEqual(<strong>actualVal:any</strong>, <strong>expectedVal:any</strong>, <i>message:str|err</i>) </td>
        <td> - tests the equality between the 1st and 2nd arguments by using the 'same value comparison' (<mark>===</mark>) <br>
          - does nothing if the compared values are NOT equal, otherwise throws an assertion error (optionally with the passed message) <br>
          - cannot compare objects = throws an assertion error
          <span id="browserSupport" title="updated : 2019-08-29">
            <span><i class="fab fa-node-js"></i> 0.1.21 </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.rejects(<strong>asyncFn|promise</strong>, <i>Class|RegExp|obj|err|fn</i>, <i>message:str</i>) </td>
        <td> - does nothing if the <strong>asyncFn|promise</strong> returns a rejected promise, otherwise throwns an assertion error (optionally with the passed message) <br>
          - does not throw an assertion error if the rejected promise data's Class matches with the passed <i>Class</i> <br>
          - does not throw an assertion error if the rejected promise data matches with the passed <i>RegExp</i> (uses the <mark>.toString()</mark> on the rejected data to compare) <br>
          - does not throw an assertion error if the rejected promise data's properties are strict equal with the passed <i>obj</i> properties <br>
          - does not throw an assertion error if the rejected promise error object instance <mark>name</mark> and <mark>message</mark> properties are strictly equal with the passed <i>err</i> object properties <br>
          - does not throw an assertion error if the promise is rejected and <i>fn</i> returns <mark>true</mark>
          <span id="browserSupport" title="updated : 2019-09-01">
            <span><i class="fab fa-node-js"></i> 10.0.0 </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.strictEqual(<strong>actualVal:any</strong>, <strong>expectedVal:any</strong>, <i>message:str|err</i>) </td>
        <td> - tests the equality between the 1st and 2nd arguments by using the 'same value comparison' (<mark>===</mark>) <br>
          - does nothing if the compared values are equal, otherwise throws an assertion error (optionally with the passed message) <br>
          - cannot compare objects = throws an assertion error
          <span id="browserSupport" title="updated : 2019-08-29">
            <span><i class="fab fa-node-js"></i> 0.1.21 </span>
          </span>
        </td>
      </tr>
      <tr>
        <td> <strong>assert</strong>.throws(<strong>fn</strong>, <i>Class|RegExp|obj|err|fn</i>, <i>message:str</i>) </td>
        <td> - does nothing if the <strong>fn</strong> does throws an error otherwise throws an assertion error (optionally with the passed message)<br>
          - does not throw an assertion error if the thrown error's Class matches with the passed <i>Class</i> <br>
          - does not throw an assertion error if the <i>RegExp</i> matches with the thrown error (uses the <mark>.toString()</mark> on the thrown error to compare) <br>
          - does not throw an assertion error if the <i>obj</i> properties are strict equal with the thrown error object's <br>
          - does not throw an assertion error if the <i>err</i> object instance <mark>name</mark> and <mark>message</mark> properties are strictly equal with the thrown error object's <br>
          - does not throw an assertion error if the <i>fn</i> returns <mark>true</mark>
          <span id="browserSupport" title="updated : 2019-09-01">
            <span><i class="fab fa-node-js"></i> 0.1.21 </span>
            <span><i class="fab fa-node-js"></i> 4.2.0 arrow function allowed </span>
            <span><i class="fab fa-node-js"></i> 9.9.0 <i>err</i> can be object </span>
            <span><i class="fab fa-node-js"></i> 9.9.0 <i>err</i> can be object </span>
          </span>
        </td>
      </tr>
      <tr>
        <td>|</td>
        <td></td>
      </tr>
      <tr>
        <td colspan="2"> AssertionError </td>
      </tr>
      <tr>
        <td>
          <lit>assert</lit>.<a href="https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror" target="_blank">AssertionError</a>
        </td>
        <td>
          - describes comparison differences
        </td>
      </tr>
    </table>
    <h2 style="color:green;"><u> Notes : </u></h2>
    <details class="example" id="notes">
      <summary> Notes :</summary>
    </details>
    <h2 style="color:green;"><u> Useful Links : </u></h2>
    <p><a href="https://nodejs.org/dist/latest-v12.x/docs/api/assert.html" target="_blanc"> Node.js Assertion Testing </a></p>
    <h2 style="color:green;"><u> Remember This : </u></h2>

    <h2 style="color:green;"><u> Description and Demonstration : </u></h2>
    <p> - the assertion module provides functionalities to verify invariants, it throws an AssertionError instance (craches the process) if the assertion fails <u>otherwise does nothing</u></p>
    <p> - legacy assert used lose comparison (<mark>==</mark>), strict mode <u>(supported from v9.9.0)</u> usess strict comparison (<mark>====</mark>) </p>
    <pre>
// strict import ------------
    import { strict as assert } from 'node:assert':
    import assert from 'node:assert/strict';
    
    assert.deepEqual(['1', 2], [1, 2]);                 // throws an AssertionError
    
// legacy import ------------
    import assert from 'node:assert';                 // -! legacy assert uses loose comparison (<mark>==</mark>) so basically don't use it!
    
    assert.deepEqual(['1', 2], [1, 2]);               // does not throw
    </pre>
    <hr>
    <!-------------------------------------------------------------------------------------------------------------------------------->
    <h3 class="header"> The <mark>assert()</mark> / <mark>ok()</mark> / <mark>fail()</mark> / <mark>ifError()</mark> / <mark>equal()</mark> / <mark>strictEqual()</mark> / <mark>notEqual()</mark> / <mark>notStrictEqual()</mark> /  methods </h3>
    <details class="example" open>
      <summary> Example : </summary>
      <h4 class="header"> The <mark>assert()</mark> / <mark>ok()</mark> methods </h4>
      <pre>
    import assert from 'node:assert/strict';                 // -! legacy assert uses loose comparison (==) so basically don't use it!
    
    assert('ok');                               // doesn't do anything
    
    assert(0, Error("It's 0"))                  // throws Error("It's 0")
    assert(0, "It's 0")                           // throws AssertionError with the passed message
    
    assert.ok(0, Error("It's 0"))               // does the same as above
    assert.ok(0, "It's 0")
      </pre>
      <hr>
      <!-------------------------------------------------------------------------------------------------------------------------------->
      <h4 class="header"> The <mark>fail()</mark> / <mark>ifError()</mark> methods </h4>
      <pre>
      
      
      
      
      </pre>
    
    
      <hr>
      <!-------------------------------------------------------------------------------------------------------------------------------->
      <h4 style="color:darkblue;"><u> <mark>equal()</mark> / <mark>strictEqual()</mark> / <mark>notEqual()</mark> / <mark>notStrictEqual()</mark> TEST </u></h4>
      <pre style="margin-bottom:1px;">
    const assert = require('assert');
    
// cannot compare objects = assertion error thrown automatically ----------------
    try {
        assert.equal({}, {});
    } catch(err) {
        console.log(err);
    }
    
// equal() uses the 'abstract equality comparison' ------------------------------
    assert.equal(0, false, 'assertion failed');                                  // no assertion error is thrown because this assertion uses the 'abstract equality comparison' (==) therefore these values are the same   
    
// strictEqual() uses the 'same value comparison' -------------------------------
    try {
        assert.strictEqual(0, false, 'assertion failed');                        // assertion error is thrown because this assertion uses the 'same value comparison' (===) therefore these values are not the same  
    } catch(err) {
        console.log(err);
    }
    
// notEqual() uses the 'abstract equality comparison' ---------------------------
    try {
        assert.notEqual(0, false, 'assertion failed');                           // assertion error is thrown because the assertion uses the 'abstract equality comparison' (==) so these values are considered the same   
    } catch(err) {
        console.log(err);
    }
    
// notStrictEqual() uses the 'same value comparison' ----------------------------
    assert.notStrictEqual(0, false, 'assertion failed');                         // no assertion error is thrown because this assertion uses the 'same value comparison' (===) therefore thes values are not the same     
    </pre>
      <pre class="cmd" style="margin-top:1px;">
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\02 equal() strictEqual() notEqual() notStrictEqual() TEST> node main
        AssertionError [ERR_ASSERTION]: {} == {}                                 // -! assert.equal({}, {})
            at Object.&lt;anonymous&gt; (D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\02 equal() strictEqual() notEqual() notStrictEqual() TEST\main.js:5:12)
            at Module._compile (internal/modules/cjs/loader.js:774:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
            at Module.load (internal/modules/cjs/loader.js:641:32)
            at Function.Module._load (internal/modules/cjs/loader.js:556:12)
            at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
            at internal/main/run_main_module.js:17:11 {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: {},
        expected: {},
        operator: '=='
        }
        AssertionError [ERR_ASSERTION]: assertion failed                         // -! assert.strictEqual(0, false, 'assertion failed');
            at Object.&lt;anonymous&gt; (D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\02 equal() strictEqual() notEqual() notStrictEqual() TEST\main.js:15:12)
            at Module._compile (internal/modules/cjs/loader.js:774:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
            at Module.load (internal/modules/cjs/loader.js:641:32)
            at Function.Module._load (internal/modules/cjs/loader.js:556:12)
            at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
            at internal/main/run_main_module.js:17:11 {
        generatedMessage: false,
        code: 'ERR_ASSERTION',
        actual: 0,
        expected: false,
        operator: 'strictEqual'
        }
        AssertionError [ERR_ASSERTION]: assertion failed                         // -! assert.notEqual(0, false, 'assertion failed');
            at Object.&lt;anonymous&gt; (D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\02 equal() strictEqual() notEqual() notStrictEqual() TEST\main.js:22:12)
            at Module._compile (internal/modules/cjs/loader.js:774:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
            at Module.load (internal/modules/cjs/loader.js:641:32)
            at Function.Module._load (internal/modules/cjs/loader.js:556:12)
            at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
            at internal/main/run_main_module.js:17:11 {
        generatedMessage: false,
        code: 'ERR_ASSERTION',
        actual: 0,
        expected: false,
        operator: '!='
        }
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\02 equal() strictEqual() notEqual() notStrictEqual() TEST>    
    </pre>
      <hr>
      <!-------------------------------------------------------------------------------------------------------------------------------->
      <h4 style="color:darkblue;"><u> <mark>fail()</mark> / <mark>ifError()</mark> TEST </u></h4>
      <pre style="margin-bottom:1px;">
    const assert = require('assert');
    
// fail() throws assertion error with the passed message ------------------------
    try {
        assert.fail('custom failed assertion');                                  // assertion thrown with the passed message   
    } catch(err) {
        console.log(err);
    }
    
// ifError() --------------------------------------------------------------------
    assert.ifError(null);                                                        // assertion error is NOT thrown 
    try {
        assert.ifError(2021);                                                    // assertion error is thrown because the passed value is not undefined or null 
    } catch(err) {
        console.log(err);
    }
    </pre>
      <pre class="cmd" style="margin-top:1px;">
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\03 fail() ifError() TEST> node main
        AssertionError [ERR_ASSERTION]: custom failed assertion                  // -! assert.fail('custom failed assertion');
            at Object.&lt;anonymous&gt; (D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\03 fail() ifError() TEST\main.js:5:12)
            at Module._compile (internal/modules/cjs/loader.js:774:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
            at Module.load (internal/modules/cjs/loader.js:641:32)
            at Function.Module._load (internal/modules/cjs/loader.js:556:12)
            at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
            at internal/main/run_main_module.js:17:11 {
        generatedMessage: false,
        code: 'ERR_ASSERTION',
        actual: undefined,
        expected: undefined,
        operator: 'fail'
        }
        AssertionError [ERR_ASSERTION]: ifError got unwanted exception: 2021     // -! assert.ifError(2021);
            at Object.&lt;anonymous&gt; (D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\03 fail() ifError() TEST\main.js:13:12)
            at Module._compile (internal/modules/cjs/loader.js:774:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
            at Module.load (internal/modules/cjs/loader.js:641:32)
            at Function.Module._load (internal/modules/cjs/loader.js:556:12)
            at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
            at internal/main/run_main_module.js:17:11 {
        generatedMessage: false,
        code: 'ERR_ASSERTION',
        actual: 2021,
        expected: null,
        operator: 'ifError'
        }
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\03 fail() ifError() TEST>    
    </pre>
    </details>

    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

    <hr>
    <!-------------------------------------------------------------------------------------------------------------------------------->
    <h2 style="color:darkblue;"><u> <mark>deepEqual()</mark> / <mark>deepStrictEqual()</mark> / <mark>notDeepEqual()</mark> / <mark>notDeepStrictEqual()</mark> methods </u></h2>
    <pre class="syntax">
SYNTAX :    <strong>assert</strong>.deepEqual(<strong>actual:any</strong>, <strong>expected:any</strong>, <i>message:str|err</i>)          // deeply compares the equality between the 1st and 2nd arguments (can compare objects)   
                                                                                    does nothing if the compared arguments are equal, otherwise throws an assertion error (optionally with the passed message)   
                                                                                    primitive values are compared with the 'Abstract Equality Comparison' (<mark>==</mark>) (in strict mode it uses the (<mark>===</mark>) comparison)  
                                                                                    only enumerable own properties are considered 
                                                                                    Error names and messages are always compared, even if they aren't enumerable properties 
                                                                                    Object wrappers are compared both as objects and unwarpped values 
                                                                                    Object / Map / Set properties|items are compared unordered 
                                                                                    does not test object prototypes  
                                                                                    <span style="color:orange;">deprecated use the <mark>deepStrictEqual</mark> method instead</span>   
    
            <strong>assert</strong>.deepStrictEqual(<strong>actual:any</strong>, <strong>expected:any</strong>, <i>message:str|err</i>)    // deeply compares the equality between the 1st and 2nd arguments (can compare objects)   
                                                                                    does nothing if the compared arguments are equal, otherwise throws an assertion error (optionally with the passed message)   
                                                                                    primitive values are compared with the 'Same Value Equality' (<mark>===</mark>) 
                                                                                    only enumerable own properties are considered
                                                                                    compares enumerable own Symbol properties
                                                                                    Error names and messages are always compared, even if they aren't enumerable properties
                                                                                    Object wrappers are compared both as objects and unwarpped values
                                                                                    Object / Map / Set properties|items are compared unordered 
                                                                                    compares prototypes by using the 'Same Value Comparison' (<mark>===</mark>)   
                                                                                    
            <strong>assert</strong>.notDeepEqual(<strong>actual:any</strong>, <strong>expected:any</strong>, <i>message:str|err</i>)       // deeply compares the equality between the 1st and 2nd arguments (can compare objects)   
                                                                                    does nothing if the compared arguments are NOT equal, otherwise throws an assertion error (optionally with the passed message)   
                                                                                    primitive values are compared with the 'Abstract Equality Comparison' (<mark>==</mark>) (in strict mode it uses the (<mark>===</mark>) comparison)  
                                                                                    only enumerable own properties are considered 
                                                                                    Error names and messages are always compared, even if they aren't enumerable properties 
                                                                                    Object wrappers are compared both as objects and unwarpped values 
                                                                                    Object / Map / Set properties|items are compared unordered 
                                                                                    does not test object prototypes  
                                                                                    <span style="color:orange;">deprecated use the <mark>notDeepStrictEqual</mark> method instead</span>   
            
            <strong>assert</strong>.notDeepStrictEqual(<strong>actual:any</strong>, <strong>expected:any</strong>, <i>message:str|err</i>) // deeply compares the equality between the 1st and 2nd arguments (can compare objects)   
                                                                                    does nothing if the compared arguments are NOT equal, otherwise throws an assertion error (optionally with the passed message)   
                                                                                    primitive values are compared with the 'Same Value Equality' (<mark>===</mark>) 
                                                                                    only enumerable own properties are considered
                                                                                    compares enumerable own Symbol properties
                                                                                    Error names and messages are always compared, even if they aren't enumerable properties
                                                                                    Object wrappers are compared both as objects and unwarpped values
                                                                                    Object / Map / Set properties|items are compared unordered 
                                                                                    compares prototypes by using the 'Same Value Comparison' (<mark>===</mark>)
    </pre>
    <pre>
    const assert = require('assert');                                            // legacy mode used (strict mode not used in order to demo 'abstract equality comparison')    
    
    var obj1 = {p1:'val1', p2:21, p3:false};
    var obj2 = {p1:'val1', p2:21, p3:false};
    var obj3 = {p1:'val1', p2:21, p3:0};
    
// deepEqual() / deepStrictEqual() ----------------------------------------------
    assert.deepEqual(obj1, obj2,);                                               // assertion error not thrown (objects are equal)
    
    assert.deepEqual(obj2, obj3);                                                // assertion error not thrown because this assertion method uses the 'Abstract Equality Comparison' (==)   
    assert.deepStrictEqual(obj2, obj3);                                          // assertion error is thrown because this assertion method uses the 'Same Value Comparion' (===) (objects are not equal)   
    
// notDeepEqual() / notDeepStrictEqual() ----------------------------------------
    assert.notDeepEqual(obj1, obj2);                                             // assertion error is thrown (objects are equal)
    
    assert.notDeepEqual(obj2, obj3);                                             // assertion error is thrown because this assertion method uses the 'Abstract Equality Comparison' (==)   
    assert.notDeepStrictEqual(obj2, obj3);                                       // assertion error is NOT thrown because this assertion method uses the 'Same Value Comparion' (===) (objects are not equal)   
    </pre>
    <details class="example">
      <summary> Example : </summary>
      <h4 style="color:darkblue;"><u> <mark>deepEqual()</mark> / <mark>deepStrictEqual()</mark> / <mark>notDeepEqual()</mark> / <mark>notDeepStrictEqual()</mark> TEST </u></h4>
      <pre style="margin-bottom:1px;">
    const assert = require('assert');

    var obj1 = {p1:"val1", p2:21, p3:true, p4:null};
    var obj2 = {p1:"val1", p2:21, p3:true, p4:null};
    var obj3 = {p1:"val1", p2:21, p3:1, p4:null};
    
// deepEqual() deepStrictEqual() -----------------------------------
        assert.deepEqual(obj1, obj2);                                            // no assertion error is thrown (objects are the same);
        assert.deepEqual(obj1, obj3);                                            // no assertion error is thrown because the assertion funciton uses 'Abstract Equality Comparison' (==) 
        try {
            assert.deepStrictEqual(obj1, obj3);                                  // assertion error is thrown because the assertion function uses the 'Same Value Comparison'  
        } catch(err) {
            console.log(err);
        }
    
// notDeepEqual() / notDeepStrictEqual() ---------------------------
        try {
            assert.notDeepEqual(obj1, obj3);                                     // assertion error is thrown because objects are considered the same 'Abstract Equality Comparison' (==) used   
        } catch(err) {
            console.log(err);
        }
        assert.notDeepStrictEqual(obj1, obj3);                                   // assertion error is not thrown because the object aren't considered the same 'Equal Value Comparison' (===) used       
    </pre>
      <pre class="cmd" style="margin-top:1px;">
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\04 deepEqual() deepStrictEqual() notDeepEqual() notDeepStrictEqual() TEST> node main 
        AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:      // -! assert.deepStrictEqual(obj1, obj3);
        + actual - expected

        {
            p1: 'val1',
            p2: 21,
        +   p3: true,
        -   p3: 1,
            p4: null
        }
            at Object.&lt;anonymous&gt; (D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\04 deepEqual() deepStrictEqual() notDeepEqual() notDeepStrictEqual() TEST\main.js:11:16)
            at Module._compile (internal/modules/cjs/loader.js:774:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
            at Module.load (internal/modules/cjs/loader.js:641:32)
            at Function.Module._load (internal/modules/cjs/loader.js:556:12)
            at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
            at internal/main/run_main_module.js:17:11 {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: [Object],
        expected: [Object],
        operator: 'deepStrictEqual'
        }
        AssertionError [ERR_ASSERTION]: Expected values not to be loosely deep-equal:   // -! assert.notDeepEqual(obj1, obj3);
        {
        p1: 'val1',
        p2: 21,
        p3: true,
        p4: null
        }
        should not loosely deep-equal
        {
        p1: 'val1',
        p2: 21,
        p3: 1,
        p4: null
        }
            at Object.&lt;anonymous&gt; (D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\04 deepEqual() deepStrictEqual() notDeepEqual() notDeepStrictEqual() TEST\main.js:18:16)
            at Module._compile (internal/modules/cjs/loader.js:774:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
            at Module.load (internal/modules/cjs/loader.js:641:32)
            at Function.Module._load (internal/modules/cjs/loader.js:556:12)
            at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
            at internal/main/run_main_module.js:17:11 {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: [Object],
        expected: [Object],
        operator: 'notDeepEqual'
        }
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\04 deepEqual() deepStrictEqual() notDeepEqual() notDeepStrictEqual() TEST>      
    </pre>
      <hr>
      <!-------------------------------------------------------------------------------------------------------------------------------->
      <pre style="margin-bottom:1px;">
    const assert = require('assert');
    
    var obj1 = {p1:'val1', p2:21};
    var obj2 = Object.create(obj1);                                              // obj2 is the prototype of obj1
    
    obj2.p1 = 'val1';                                                            // assigning the same properties to obj2 (to get the same object, only their prototype differs)
    obj2.p2 = 21;
    
    assert.deepEqual(obj1, obj2);                                                // not assertion error thrown because this assertion function does not compares prototypes 
    assert.deepStrictEqual(obj1, obj2);                                          // assertion error is thrown, this assertion function compares object prototypes which aren't the same at this case       
    </pre>
      <pre class="cmd" style="margin-top:1px;">
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\05 deepEqual() VS deepStrictEqual() TEST> node main    
        assert.js:89
        throw new AssertionError(obj);                                           // -! assert.deepStrictEqual(obj1, obj2);
        ^
        AssertionError [ERR_ASSERTION]: Values identical but not reference-equal:
        {
        p1: 'val1',
        p2: 21
        }
            at Object.&lt;anonymous&gt; (D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\05 deepEqual() VS deepStrictEqual() TEST\main.js:10:8)
            at Module._compile (internal/modules/cjs/loader.js:774:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
            at Module.load (internal/modules/cjs/loader.js:641:32)
            at Function.Module._load (internal/modules/cjs/loader.js:556:12)
            at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
            at internal/main/run_main_module.js:17:11 {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: [Object],
        expected: [Object],
        operator: 'deepStrictEqual'
        }
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\05 deepEqual() VS deepStrictEqual() TEST>         
    </pre>
    </details>
    <hr>
    <!-------------------------------------------------------------------------------------------------------------------------------->
    <h2 style="color:darkblue;"><u> <mark>throws()</mark> / <mark>doesNotThrow()</mark> / <mark>rejects()</mark> / <mark>doesNotReject()</mark> methods </u></h2>
    <pre class="syntax">
SYNTAX :    <strong>assert</strong>.throws(<strong>fn</strong>, <i>Class|RegExp|obj|err|fn</i>, <i>message:str</i>)              // does nothing if the <strong>fn</strong> does throws an error otherwise throws an assertion error (optionally with the passed message)    
                                                                                    does not throw an assertion error if the thrown error's Class matches with the passed <i>Class</i> 
                                                                                    does not throw an assertion error if the <i>RegExp</i> matches with the thrown error (uses the <mark>.toString()</mark> on the thrown error to compare)   
                                                                                    does not throw an assertion error if the <i>obj</i> properties are strict equal with the thrown error object's
                                                                                    does not throw an assertion error if the <i>err</i> object instance <mark>name</mark> and <mark>message</mark> properties are strictly equal with the thrown error object's   
                                                                                    does not throw an assertion error if the <i>fn</i> returns <mark>true</mark>   
                                                                                     
            <strong>assert</strong>.doesNotThrow(<strong>fn</strong>, <i>Class|RegExp|obj|err|fn</i>, <i>message:str</i>)        // does nothing if the <strong>fn</strong> does NOT throw an error
                                                                                    if <strong>fn</strong> throws an error an assertion error is thrown (with the passed message) in any situation   
                                                                                    <u>(useless method according to Node.js specification)</u>   
            
            <strong>assert</strong>.rejects(<strong>asyncFn|promise</strong>, <i>Class|RegExp|obj|err|fn</i>, <i>message:str</i>)// does nothing if the <strong>asyncFn|promise</strong> returns a rejected promise, otherwise throwns an assertion error (optionally with the passed message)   
                                                                                    does not throw an assertion error if the rejected promise data's Class matches with the passed <i>Class</i>
                                                                                    does not throw an assertion error if the rejected promise data matches with the passed <i>RegExp</i> (uses the <mark>.toString()</mark> on the rejected data to compare)   
                                                                                    does not throw an assertion error if the rejected promise data's properties are strict equal with the passed <i>obj</i> properties    
                                                                                    does not throw an assertion error if the rejected promise error object instance <mark>name</mark> and <mark>message</mark> properties are strictly equal with the passed <i>err</i> object properties   
                                                                                    does not throw an assertion error if the promise is rejected and <i>fn</i> returns <mark>true</mark>    
            
            <strong>assert</strong>.doesNotReject(<strong>asyncFn|promise</strong>, <i>Class|RegExp|obj|err|fn</i>, <i>message:str</i>)  // does nothing if the <strong>asyncFn|promise</strong> returns a resolved promise, otherwise throwns an assertion error (optionally with the passed message)   
                                                                                            if <strong>asyncFn|promise</strong> returns a rejected promise an assertion error will be thrown in any situation
                                                                                            <u>(useless method according to Node.js specification)</u>   
    </pre>
    <pre>
    const assert = require('assert');
    
    var err = new ReferenceError('custom ref err');
    err.code = 401;
    
// throws() ---------------------------------------------------------------------
    assert.throws(function(){throw err;});                                       // error thrown = no assertion error is thrown   
    
    assert.throws(funciton(){}, null, 'some message');                           // -! no error thrown by the function = assertion error is thrown by Node.js with the passed message
    
    assert.throws(function(){throw err;}, Error);                                // thrown error Class matches with the passed Class = no assertion error is thrown
    
    assert.throws(function(){throw err;}, /E/);                                  // the '.toString()' method is used on the thrown error then compared against the regular expression which matches = no assertion error is thrown   
    
    assert.throws(function(){throw err;}, {message:'custom ref err', code:401}); // the object properties are strictly equal with the thrown error object's properties = no assertion error is thrown   
    
    assert.throws(function(){throw err;}, new ReferenceError('custom ref err')); // the passed error object's 'message' and 'name' properties match with the thrown error object's ones (only the 'name' and 'message' properties must match in this situation that's why the 'code' property is not causing an assertion error)   
    
    assert.throws(function(){throw err;}, function(){return true;});             // function returns 'true' = no assertion error is thrown   
    
// doesNotThrow() ---------------------------------------------------------------
    assert.doesNotThrow(function(){});                                           // no error is thrown by the function = no assertion error is thrown   
    
    assert.doesNotThrow(function(){throw err;}, 'some message');                 // -! function throws an error = assertion error is thrown by Node.js with the provided message 
    
// rejects() --------------------------------------------------------------------
    assert.rejects(Promise.reject('rejected data'));                             // rejected promise returned by the function = no assertion error is thrown  
    
    assert.rejects(Promise.resolve(21), null, 'some message');                   // -! resolved promise = assertion error is thrown by Node.js  
    
    assert.rejects(Promise.reject(/ai/), RegExp);                                // rejected promise data's Class matches with the passed Class = no assertion error is thrown   
    
    assert.rejects(Promise.reject(false), /s/);                                  // uses the '.toString()' method on the rejected promise's data in order to compare with the RegExp what matches in this situation = no assertion error is thrown   
    
    assert.rejects(Promise.reject({p1:'val'}), {p1:'val'});                      // the rejected promise's object properties are strict equal with the passed object = no assertion error is thrown  
    
    assert.rejects(Promise.reject(err), ReferenceError('custom ref err'));       // the rejected promise error object properties match with the passed error object properties = no assertion error is thrown   
    
    assert.rejects(Promise.reject(21), function(){return true});                 // function returns 'true' = no assertion error is thrown
    
// doesNotReject() --------------------------------------------------------------
    assert.doesNotReject(Promise.resolve('resolved data'));                      // resolved promise returned = no assertion error is thrown 
    
    assert.doesNotReject(Promise.reject('rejected data'));                       // -! rejected promise = assertion error is thrown by Node.js   
    </pre>
    <details class="example">
      <summary> Example : </summary>
      <h4 style="color:darkblue;"><u> <mark>throws()</mark> / <mark>doesNotThrow()</mark> TEST </u></h4>
      <pre style="margin-bottom:1px;">
    const assert = require('assert');
    
    var err = new RangeError('custom range error!');
    err.code = 123;
    err.port = 123.033;
    
    var err2 = new RangeError('custom range error!');
    err.code = 123;
    err.port = 123.033;
    
// does not thrown an assertion error if the function throws an error ----------
    assert.throws(function(){
        throw err;
    });
    
    // no assertion error thrown (Class matches with the thrown error's Class) --
    assert.throws(function(){
        throw err;
    }, RangeError);
// no assertion error thrown (RegExp matches with the thrown error)--------------
    assert.throws(function(){
        throw err;
    }, /Ra/);                                                                    // thrown error contains thes characters 
    assert.throws(function(){
        throw err;
    }, /\s/);                                                                    // thrown error contains thes characters
    assert.throws(function(){
        throw err;                                                                    
    }, /!/);                                                                     // thrown error contains thes characters
    
// no assertion error thrown (object contains the matching properties) ----------
    assert.throws(function(){
        throw err;
    }, {message:'custom range error!', code:123, port:123.033});                 // this object is checked against the thrown error object (with deep strict equality)
    
// no assertion error thrown (error object is an equal instance) ----------------
    assert.throws(function(){
        throw err;
    }, err2);
    
// no assertion error thrown (function returns true) ----------------------------
    assert.throws(function(){
        throw err;
    }, function(){
        return true;                                                             // we could set complex conditions here 
    });
    
// ------------------------------------------------------------------------------
// doesNotThrow() ---------------------------------------------------------------
    
// no assertion error thrown (function does not throws an error) ----------------
    assert.doesNotThrow(function(){
        var result = 1 + 2;
        return result;
    });
    
// if the function throws an error the 'doesNotThrow()' method throws an assertion error in any conditions --
    assert.doesNotThrow(function(){
        throw err;
    }, ()=> true, 'custom assertion message!');
    </pre>
      <pre class="cmd" style="margin-top:1px;">
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\06 throws() doesNotThrow() TEST> node main                                                                                                                
        assert.js:89
        throw new AssertionError(obj);                                           // -! assert.doesNotThrow(function(){throw err;}, ()=> true, 'custom assertion message!');     // error thrown = assertion error 
        ^
        
        AssertionError [ERR_ASSERTION]: Got unwanted exception: custom assertion message!
        Actual message: "custom range error!"
            at Object.&lt;anonymous&gt; (D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\06 throws() doesNotThrow() TEST\main.js:59:8)
        [90m    at Module._compile (internal/modules/cjs/loader.js:774:30)[39m
        [90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)[39m
        [90m    at Module.load (internal/modules/cjs/loader.js:641:32)[39m
        [90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)[39m
        [90m    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)[39m
        [90m    at internal/main/run_main_module.js:17:11[39m {
        generatedMessage: [33mfalse[39m,
        code: [32m'ERR_ASSERTION'[39m,
        actual: [36m[RangeError][39m,
        expected: [36m[Function][39m,
        operator: [32m'doesNotThrow'[39m
        }
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\06 throws() doesNotThrow() TEST>    
    </pre>
      <hr>
      <!-------------------------------------------------------------------------------------------------------------------------------->
      <h4 style="color:darkblue;"><u> <mark>rejects()</mark> / <mark>doesNotReject()</mark> TEST </u></h4>
      <pre style="margin-bottom:1px;">
    const assert = require('assert');
        
// no assertion error thrown (rejected promise) ---------------------------------
    assert.rejects( Promise.reject([1, 2, 3]) );                                 
    
// no assertion error thrown (rejected promise result Class matches) ------------
    assert.rejects( Promise.reject([1, 2, 3]), Array );
    
// no assertion error thrown (rejected promise result matches with RegExp) ------
    assert.rejects( async function(){ throw [1, 2, 3]}, /,/);
    assert.rejects( async function(){ throw [1, 2, 3]}, /2/);
    
// no assertion error thrown (rejected promise result matches with the passed obj) 
    assert.rejects( Promise.reject([1, 2, 3]), [1, 2, 3]);
    
// no assertion error thrown (function returns 'true') --------------------------
    assert.rejects( Promise.reject(21), ()=>{ return true;} );
    
// ------------------------------------------------------------------------------
// doesNotReject() --------------------------------------------------------------
    
// no assertion error thrown (resolved promise is passed ) ----------------------
    assert.doesNotReject( Promise.resolve('resolved promise data'));
    
// assertion error is thrown (rejected promise is passed ) ----------------------
    assert.doesNotReject( Promise.reject('rejected'), null, 'rejected baze' );   // rejected promise will throw an assertion error in any condition    
    </pre>
      <pre class="cmd" style="margin-top:1px;">
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\07 rejects() doesNotReject() TEST> node main                                         
        (node:12440) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Got unwanted rejection: rejected baze        // -! assert.doesNotReject( Promise.reject('rejected'), null, 'rejected baze' );
        Actual message: "undefined"
        (node:12440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
        (node:12440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    PS D:\safe\code +\my site\03 improuve\learn webdesign\04 node.js\assert\07 rejects() doesNotReject() TEST>    
    </pre>
    </details>

    <br><br>
  </body>
</html>